language: minimal
os:
  - linux
before_install:
  - sudo apt-get update && sudo apt-get install
    ncurses-dev 
install:
  - curl -L https://ziglang.org/builds/zig-linux-x86_64-0.4.0+3eca5a42.tar.xz | tar xJ
git:
  depth: false
script:
  - zig-linux-*/zig version
  - zig-linux-*/zig build --override-std-dir zig-linux-*/lib/zig/std