language: bash
os:
  - linux
install:
  - curl -L https://ziglang.org/builds/zig-linux-x86_64-0.4.0+3eca5a42.tar.xz | tar xJ
git:
  depth: false
script:
  - zig-linux-*/zig version
  - zig-linux-*/zig build test
  - zig-linux-*/zig build